# Generated by Django 5.1.7 on 2025-03-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('added_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
